### ISSUE TITLE
Transférer les changement faits pour la prérelease sur la master

### ISSUE THREAD

**Issue by Ndr6** [Ndr6/Casse-Brique-ISN#110]

**Comment by DufDuf62** [comment]
Tu veux que je le fasses ?

**Comment by Ndr6** [comment]
Nan je vais m'en occuper, merci quand même :)

**Comment by Apachaisan** [comment]
j'ai pas compris pourquoi vous avez pas fait la pre-release sur le master dès le début...

**Comment by Ndr6** [comment]
Parce que ! Maintenant c'est fait
