### ISSUE TITLE
Niveau 2

### ISSUE THREAD

**Issue by Apachaisan** [Ndr6/Casse-Brique-ISN#121]
Il manque plein de trucs sur le niveau 2 (orbite) qui sont sur le proto et qu'on pourrait mettre
-aucun sons
-pas d'anim de barre de power-ups
-pas d'anim de barre qui s'agrandi
-balle très rapide comparé au proto (c'est normale ou pas ??)

**Comment by Ndr6** [comment]
- Les sons sont là
- La même que les autres niveaux
- Pareil
- Nan ça c'est pas normal, tu veux bien regarder pourquoi ça fait ça ?

**Comment by DufDuf62** [comment]
Peut-être parce que le code n'est pas à jour

**Comment by Ndr6** [comment]
Nan mais on fait tout sur le proto et a la fin on applique les graphismes /
patterns des niveaux
Sinon on s'en sort pas avec 5 niveaux a toujours mettre a jour
