### ISSUE TITLE
Style des compteurs de combo/score

### ISSUE THREAD

**Issue by Apachaisan** [Ndr6/Casse-Brique-ISN#123]
Quelle police/taille/couleur pour le compteur de combo et de score ? balancez des idées.

**Comment by Ndr6** [comment]
Fixedsys, Pas trop gros, Blanc pour la visibilité

**Comment by Ndr6** [comment]
Tu comptes les placer ou sur le canvas ?

**Comment by Apachaisan** [comment]
à gauche au dessus des vies

**Comment by Ndr6** [comment]
Pas possible, la raquette passe dessus

**Comment by Apachaisan** [comment]
non

**Comment by Ndr6** [comment]
Bah, si, j'ai positionné les vies au pixel près au dessous de la raquette

**Comment by Apachaisan** [comment]
![image](https://cloud.githubusercontent.com/assets/26092948/26274375/055b3564-3d49-11e7-830a-c1648f61f732.png)

**Comment by Ndr6** [comment]
C'est vachement mal placé je trouve, et le fond est bleu

**Comment by Apachaisan** [comment]
oui j'ai pas encore trouvé comment changer la couleur de la police, et je voie pas vraiment ou le mettre, je trouve ca pas mal, je le mettrais plus bas je pense

**Comment by Ndr6** [comment]
Essaie de le poser a droite du compteur de vie, en dessous de la raquette

**Comment by Apachaisan** [comment]
![image](https://cloud.githubusercontent.com/assets/26092948/26274416/eeb6036a-3d49-11e7-85d6-fc378fa089b4.png)

**Comment by Apachaisan** [comment]
rpz

**Comment by Ndr6** [comment]
Un chouia plus bas et c'est bon je pense

**Comment by Apachaisan** [comment]
Le meilleur score actuel, est-ce que vous pouvez faire mieux ? 
![image](https://cloud.githubusercontent.com/assets/26092948/26274500/7ee07de8-3d4b-11e7-87dc-fbc665c83e64.png)

**Comment by Ndr6** [comment]
Ouaip parfait

**Comment by Ndr6** [comment]
Manque plus que dire ce que c'est et changer les couleurs

**Comment by Ndr6** [comment]
Salut @Apachaisan , Il faudrait que tu aies fini aujourd'hui stp

**Comment by Ndr6** [comment]
Hors délai
