### ISSUE TITLE
Musiques des niveaux

### ISSUE THREAD

**Issue by Ndr6** [Ndr6/Casse-Brique-ISN#124]
- __Terre --> Through time and space http://www.newgrounds.com/audio/listen/572657__
- __Orbit --> Space Corsair http://www.newgrounds.com/audio/listen/712963__
- __Espace --> Clear your mind https://www.jamendo.com/track/1255406/clear-your-mind__
- __Mars --> Planting Roots https://www.youtube.com/watch?v=POf_PuyTlhw__

**Comment by Ndr6** [comment]
@DufDuf62 @Naijib @Apachaisan Vous pensez quoi des musiques pour Terre, Espace et Mars ?

**Comment by DufDuf62** [comment]
Terre et Espace sont bien, Mars je suis pas fan mais bon ça passe

**Comment by Ndr6** [comment]
Vas-y trouve mieux :)

**Comment by Ndr6** [comment]
On a tout
