### ISSUE TITLE
Mettre à jour le js des niveaux modifiés

### ISSUE THREAD

**Issue by Ndr6** [Ndr6/Casse-Brique-ISN#129]
Anthony, il faudrait que tu appliques les mises a jour du levelProto.js aux niveaux : 
- Niveau 3
- levelBoss

Après que @Apachaisan ait fini ses compteurs
Si possible avant ce soir, merci beaucoup

Je m'occuperai de placer les assets et les effets sonores

**Comment by DufDuf62** [comment]
Fait
