### ISSUE TITLE
Besoin des assets graphiques

### ISSUE THREAD

**Issue by DufDuf62** [Ndr6/Casse-Brique-ISN#13]
Il nous faut des assets graphiques pour : 
- Le fond
- Les balles (Nordic)
- Les briques (Nordic)

Pour les tous les niveaux !

**Comment by Ndr6** [comment]
Les assets pour la niveau espace ont été faits par Gabin, il ne manque plus que ceux pour le niveau nordique

**Comment by Ndr6** [comment]
J'ai mis a jour le 1er post @Naijib

**Comment by Ndr6** [comment]
Tous les assets sont faits
