### ISSUE TITLE
Ajuster la difficulté du boss

### ISSUE THREAD

**Issue by Ndr6** [Ndr6/Casse-Brique-ISN#132]
La difficulté normale est très bien, cependant je viens de découvrir le mode Hard
Il est impossible, juste parce qu'il y a trop de projectiles, il faudrait garder (voire diminuer un peu en mode normal) le nombre de projectile mais augmenter les dégats et changer la couleur des projectiles en Hard (pour donner un repère visuel)

**Comment by DufDuf62** [comment]
Je fais ça cette après-midi 😉

**Comment by Ndr6** [comment]
Merci ^^ Juste au moment ou je t'envoie un SMS ^^

**Comment by DufDuf62** [comment]
C'est réglé
