### ISSUE TITLE
Patterns des niveaux

### ISSUE THREAD

**Issue by Ndr6** [Ndr6/Casse-Brique-ISN#134]
Je vais stocker les patterns ici pour pas les perdre

**Comment by Ndr6** [comment]
Pattern 2 - Orbit : 
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,
1, 2, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 2, 1,
1, 2, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 2, 1,
1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1];

**Comment by Ndr6** [comment]
Pattern 1 - Nordic : 
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1];

**Comment by Ndr6** [comment]
Pattern 3 - Space : 
[0, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 0,
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2,
2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2,
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
0, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 0];

**Comment by Ndr6** [comment]
Pattern 4 - Mars : 
Fait manuellement par @DufDuf62

**Comment by DufDuf62** [comment]
Tu m'as volé mon pull request !

**Comment by Ndr6** [comment]
Oui mais c'est justifié, je vais le faire tester
