### ISSUE TITLE
Choix des briques sur le niveau orbite

### ISSUE THREAD

**Issue by Ndr6** [Ndr6/Casse-Brique-ISN#138]
Les assets des briques sont mal choisis, il faudrait utiliser brique1 et brique2

**Comment by DufDuf62** [comment]
Je ne comprends pas. Les briques utilisées sont déjà les briques 1 et 2

**Comment by Ndr6** [comment]
Il faut utiliser la brique 1 (marron cassée) et 2 (marron)

**Comment by Ndr6** [comment]
ou 2 et 4

**Comment by Ndr6** [comment]
(marron et blanche)
Actuellement c'est 2 et 3

**Comment by DufDuf62** [comment]
Ah d'accord en faite j'ai mis les briques là pour mieux voir le pattern

**Comment by DufDuf62** [comment]
J'ai mis 2 et 4 on peut changer mais là on voit le pattern je trouve ça mieux

**Comment by Ndr6** [comment]
Je regarde

**Comment by Ndr6** [comment]
C'est bon, merci :)
