### ISSUE TITLE
Crash du niveau Mars (pupUnstop)

### ISSUE THREAD

**Issue by Ndr6** [Ndr6/Casse-Brique-ISN#141]
Si on touche un pupUnstop, le niveau crash

**Comment by DufDuf62** [comment]
Je ne comprends pas comment ce bug se produit

**Comment by Ndr6** [comment]
Tu arrive a le reproduire ?

**Comment by DufDuf62** [comment]
Non

**Comment by Ndr6** [comment]
Peut être que c'est une erreur de copie de ma part

**Comment by DufDuf62** [comment]
Je pense pas j'ai vérifié, ça te la fait combien de fois ?

**Comment by Ndr6** [comment]
A chaque fois

**Comment by Ndr6** [comment]
Le pup disparaît a moitié, puis le son se lance puis rien ne bouge

Le dim. 21 mai 2017 à 22:10, Sébastien Bernard <sebas981@gmail.com> a
écrit :

> A chaque fois
>

**Comment by Ndr6** [comment]
Je vais me coucher, bonne nuit

**Comment by DufDuf62** [comment]
Bonne nuit, on verra demain pour le bug

**Comment by DufDuf62** [comment]
Réglé
