### ISSUE TITLE
Manque des trucs sur niveau mars

### ISSUE THREAD

**Issue by Apachaisan** [Ndr6/Casse-Brique-ISN#147]
alors Anthony c'est bien gentil d'ajouter les combo mais t'as oublié d'ajouter la police:
"
@font-face {
         font-family: Fixedsys;
         src: url("FSEX300.ttf");
}
" dans levelMars.css

et le fichier "FSEX300.ttf" à ajouter dans le dossier Mars

**Comment by DufDuf62** [comment]
Fait
