### ISSUE TITLE
Le Réchauffement climatique

### ISSUE THREAD

**Issue by Apachaisan** [Ndr6/Casse-Brique-ISN#2]
Le réchauffement climatique, également appelé réchauffement planétaire (et parfois réchauffement global par mauvaise traduction du faux ami anglais global), est un phénomène d'augmentation des températures sur la plus grande partie des océans et de l'atmosphère terrestre, mesuré à l'échelle mondiale sur plusieurs décennies, et qui traduit une augmentation de la quantité de chaleur retenue à la surface terrestre. Dans son acception commune, ce terme est appliqué à une tendance au réchauffement global observé depuis le début du xxe siècle, entraînant, entre autres conséquences, un changement (ou dérèglement) climatique global.

En 1988, l'ONU crée le Groupe d'experts intergouvernemental sur l'évolution du climat (GIEC) chargé de faire une synthèse des études scientifiques sur cette question. Dans son quatrième rapport, auquel ont participé plus de 2 500 scientifiques de 130 pays, le GIEC affirme que le réchauffement climatique depuis 1950 est très probablement dû à l'augmentation des gaz à effet de serre d'origine anthropique. Les conclusions du GIEC ont été approuvées par plus de quarante sociétés scientifiques et académies des sciences, y compris l'ensemble des académies nationales des sciences des grands pays industrialisés3. Dans une étude publiée fin 2012, qui a compilé et comparé des simulations issues de vingt modèles informatiques différents et des informations issues des observations satellites, une équipe de climatologues du Laboratoire national de Lawrence Livermore du département de l'Énergie des États-Unis (DoE) et de 16 autres organisations a conclu que les changements de température de la troposphère et de la stratosphère sont bien réels et qu'ils sont clairement liés aux activités humaines.

Les projections des modèles climatiques présentées dans le dernier rapport du GIEC indiquent que la température de surface du globe est susceptible d'augmenter de 1,1 à 6,4 °C supplémentaires au cours du xxie siècle. Les différences entre les projections proviennent de l'utilisation de modèles ayant des sensibilités différentes pour les concentrations de gaz à effet de serre et utilisant différentes estimations pour les émissions futures. La plupart des études portent sur la période allant jusqu'à l'an 2100. Cependant, le réchauffement devrait se poursuivre au-delà de cette date, même si les émissions s'arrêtent, en raison de la grande capacité calorifique des océans et de la durée de vie du dioxyde de carbone et des autres gaz à effet de serre dans l'atmosphère.

Des incertitudes sur la hausse de température globale moyenne subsistent du fait de la précision des modélisations employées, et des comportements étatiques et individuels présents et futurs. Les enjeux économiques, politiques, sociaux, environnementaux, voire moraux, étant majeurs, ils suscitent des débats nombreux, à l'échelle internationale, ainsi que des controverses. Néanmoins l'impact économique, sociologique, environnemental voire géopolitique de ces projections est globalement négatif à moyen et long terme.

Observations liées au réchauffement climatique actuel

Divers changements observés dans le monde ont conduit à la conclusion de l'existence d'un réchauffement climatique planétaire :

En France, un observatoire national sur les effets du réchauffement climatique (ONERC), créé en 2001, compile les observations.

En Europe, la dernière évaluation (2012, par l'AEE) a conclu à l'imminence de nouveaux impacts négatifs, dont économiques ; comme prévu par la plupart des modèles, les températures moyennes ont augmenté en Europe, et les précipitations ont diminué au sud et augmenté au Nord. Les glaces arctiques et groenlandaises ont continué à régresser, de même que de nombreux glaciers européens (les glaciers alpins ont presque perdu deux tiers de leur masse de 1850 à 2010), alors que le permafrost s'est réchauffé et que le manteau neigeux tend à diminuer. Les crises climatiques (pics et vagues de chaleur, inondations, sécheresses) sont de plus en plus coûteuses en Europe, et inégalement réparties (notamment car les activités humaines sont croissantes dans les zones à risque ; zones qui devraient s'agrandir avec le dérèglement climatique). Sans dispositifs d'adaptation, les coûts générés par des événements extrêmes attendus (plus intenses et plus fréquents) devraient régulièrement augmenter et aggraver certaines inégalités. Selon Jacqueline McGlade, directrice de l'AEE, tous les acteurs de l’économie, dont les ménages, doivent s’adapter et réduire leurs émissions.

En Europe, la décennie 2002-2011 a été la plus chaude depuis que l'on dispose de données météorologiques (températures moyenne du sol dépassant de 1,3 °C la moyenne « préindustrielle » et qui pourraient après 2050 dépasser de 2,5 à 4 °C la moyenne des années 1961-1990).

Des dizaines de milliers de morts sont attribuées aux vagues de chaleur (plus fréquentes, plus longues). Le nombre de morts de froid en Europe devrait en revanche diminuer. Les inondations devraient augmenter au nord et les sécheresses au sud. L'Arctique se réchauffe plus vite que les autres régions européennes, entraînant un doublement de la fonte de la calotte groenlandaise de 1990 à 2010 (250 milliards de tonnes de glace perdues/an de 2005 à 2009). La mer a monté en Europe d'environ 1,7 mm/an au cours du xxe siècle, avec une accélération (3 mm/an) au cours des dernières décennies, avec des variations isostatiques locales. Des impacts sont attendus sur la flore (floraison plus précoce et/ou tardive, maladies des arbres…, mais aussi sur la faune : zoonoses, changement d'aire de répartition) et les maladies (tiques, certains moustiques et phlébotomes remontent plus au nord et en altitude). La saison pollinique est en 2012 plus longue d'environ dix jours qu'en 1960. Le plancton se modifie et — hors milieux marins — la vitesse de migration/adaptation de beaucoup d'espèces est insuffisante par rapport à la rapidité des dérèglements bio-géoclimatiques, ce qui aggrave les risques de disparition. Les rendements agricoles devraient diminuer au sud et peut-être augmenter au nord. Le chauffage hivernal est moins nécessaire, mais la climatisation estivale compense ces économies à la saison où les réacteurs nucléaires sont le plus à l'arrêt ou commencent parfois déjà à manquer d'eau pour leur refroidissement. Une nouvelle stratégie d'adaptation européenne est en préparation pour mars 2013. Un site internet Climate-ADAPT offre de l'information et des conseils sur l'adaptation au changement climatique.

Selon Greenpeace, le réchauffement se traduit par un dérèglement climatique général déjà perceptible. Les événements météorologiques extrêmes sont de plus en plus fréquents, de plus en plus intenses : canicules, sécheresses, inondations dues à des crues exceptionnelles, tempêtes, etc.

Précipitations

Selon le quatrième rapport du GIEC, la répartition des précipitations s'est modifiée au cours du xxe siècle. En particulier, les précipitations auraient fortement augmenté dans l'est de l’Amérique du Nord et du Sud, dans le nord de l'Europe et dans le nord et le centre de l'Asie, tandis qu'elles diminuaient au Sahel, en Méditerranée, en Afrique australe et dans une partie de l'Asie du Suda. D'autres experts estiment toutefois les données actuelles trop rares et incomplètes pour qu'une tendance à la hausse ou à la baisse des précipitations puisse se dégager sur des zones de cette ampleur. On observe également depuis 1988 une diminution notable de la couverture neigeuse printanière aux latitudes moyennes de l'hémisphère nord. Cette diminution est préoccupante car cette couverture neigeuse contribue à l'humidité des sols et aux ressources en eau

Fonte de la banquise

En 2005 et 2007 ont été atteints les records de minimum de l'étendue de la banquise arctique.
Plusieurs études indiquent que les banquises sont en train de se réduire. La surface des glaces de mer à la fin de l'été a connu une décroissance très rapide, passant de 8,5 millions de km2 pendant la période 1950-1975 à 5,5 millions de km2 en 2010. Le satellite spécialisé CryoSat-2 fut mis en orbite en avril 2010 après l'échec du premier satellite CryoSat en 2005. Il doit fournir des informations plus précises sur les quantités de glace polaire

2007 marque un minimum de la banquise en été. Cette année-là, les observations satellitaires constatent une accélération de la fonte de la banquise arctique, avec une perte de 20 % de la surface de la banquise d'été en un an.

Les observations menées pendant l'expédition Tara, une initiative privée sous l'égide du programme européen Damoclès (Developping Arctic Modelling and Observing Capabillities for Long-term Environmental Studies) de septembre 2006 à décembre 2007, indiquent que les modifications entamées dans l'océan Arctique sont profondes et irréversibles. Par ailleurs, le Groenland a vu ses glaciers se réduire de 230 à 80 milliards de tonnes par an de 2003 à 2005, ce qui contribuerait à 10 % des 3 mm actuels d'élévation annuelle du niveau des mers.

Une étude datant de 2010 montre une anticorrélation et un basculement bipolaire entre les températures des pôles durant le xxe siècle : quand un pôle se réchauffe, l'autre se refroidit, et les phases de réchauffement/refroidissement se succèdent par cycles de quelques dizaines d'année. Le lien entre les deux pôles serait l'océan Atlantique. Selon les auteurs, « l'accélération récente du réchauffement de l'Arctique résulte d'un renforcement positif de la tendance au réchauffement (due à l'accroissement des gaz à effet de serre et à d'autres forçages possibles[pas clair]) par la phase de réchauffement due à la variabilité climatique multidécennale (due aux fluctuations de la circulation de l'océan Atlantique) ».

La disparition de la banquise en été diminue l'albédo de l'Arctique, renforçant le réchauffement de l'Océan Arctique pendant cette saison. Une partie de la chaleur accumulée est transmise à l'atmosphère pendant l'hiver, modifiant la circulation des vents polaires. Ces changements entraîneraient des incursions d'air arctique aux latitudes moyennes expliquant les épisodes hivernaux rudes ayant touché les États-Unis ou l'Europe pendant les hivers 2010 à 2012. Cependant, les statistiques sur ces phénomènes récents sont encore trop peu nombreuses pour tirer une conclusion définitive.

Dans le Guardian, du 17 septembre 2012, Peter Wadhams, directeur du département de physique de l'océan polaire à l'université de Cambridge, en Angleterre, affirmait que la banquise arctique pourrait avoir totalement disparu en été d'ici 2016.

**Comment by Apachaisan** [comment]
Enfin bref, j'etais a peine à 10% donc bon flemme

**Comment by Ndr6** [comment]
Juste... Pourquoi ?

**Comment by Apachaisan** [comment]
He bha le rechauffement climatique est un probleme non ?

**Comment by Ndr6** [comment]
Oui, mais pas au niveau du projet je crois :/

**Comment by Apachaisan** [comment]
he bhe je voie qu'on est ouvert d'esprit c'est bien...

**Comment by Ndr6** [comment]
Ben on peut ouvrir un discord pour régler le changement climatique si tu veux :p
