### ISSUE TITLE
Les cotés de la raquette ne prennent pas en compte les collisions

### ISSUE THREAD

**Issue by Ndr6** [Ndr6/Casse-Brique-ISN#20]
Ou encore la balle réagit de manière étrange si elle tape sur le coté

**Comment by DufDuf62** [comment]
Les côtés de la raquette PRENNENT maintenant en compte les collisions. Et le dessous aussi.

**Comment by Ndr6** [comment]
Étrangement, même avec le dernier commit, de mon coté la balle passe toujours à travers les côtés de la raquette :/
Il faudra voir ce qui ne tourne pas rond

Je rappelle que je suis sur Firefox (v54.0)

**Comment by Ndr6** [comment]
La raquette fonctionnerait bien si elle est immobile

**Comment by Ndr6** [comment]
Le souci semble résolu par @DufDuf62 mais entraine un autre bug : 
#23
