### ISSUE TITLE
La balle accélère a fond quand elle touche la raquette au coté

### ISSUE THREAD

**Issue by Ndr6** [Ndr6/Casse-Brique-ISN#23]
Difficilement reproductible, mais c'est surprenant
Comment la balle peut-elle accélérer en touchant la raquette ?

**Comment by Ndr6** [comment]
Une solution temporaire est d'utiliser le cheat "ralentissement" (touche M), qui restaure la vitesse de la balle

**Comment by DufDuf62** [comment]
Ça arrive uniquement que quand la barre et la balle vont dans le même sens. C'est le seul moyen pas trop choquant pour que la balle ne rentre pas dans la barre et de toute façon ça ne change rien vu que si la balle touche le côté de la barre, on a perdu

**Comment by Ndr6** [comment]
Pas trop choquant ? Je pense qu'on peut trouver mieux, parce que ça se voit beaucoup quand même. 
Faudra se pencher sur ça la prochaine fois qu'on a des ordinateurs sous la main.

**Comment by DufDuf62** [comment]
Ouais même si je pense pas que ce soit très urgent que c'est juste une façon 'réglé' un bug d'une situation quasi impossible dans le jeu. Et c'est physique ! Composition des vitesses 😉

**Comment by Ndr6** [comment]
Je suis d'accord, c'est pas urgent, mais c'est pas une situation si
impossible que ça, je suis tombé dessus par hasard. Et même si c'est
physique, la balle accélère beaucoup trop et ne ralentit jamais, ce qui
rend le niveau quasi injouable

Si on ne trouve pas d'autre manière de résoudre le problème, il faudrait :
- Réduire la vitesse accélérée
- Ralentir la balle (progressivement ?) au prochain impact avec les bords
ou les briques

**Comment by DufDuf62** [comment]
Le problème est réglé. Mais il y a peut-être des bugs que j'ai pas remarqué.
