### ISSUE TITLE
Bug collisions repéré par Mr.Sautiere

### ISSUE THREAD

**Issue by DufDuf62** [Ndr6/Casse-Brique-ISN#25]
D'après Mr.Sautiere une position spécifique de la balle par rapport aux briques causerait un Bug.

**Comment by Ndr6** [comment]
Bien vu, j'avais oublié
Faudra qu'on voit ça

**Comment by DufDuf62** [comment]
Alors je pense avoir réglé tous les bugs de collisions même celui qui enlever plusieurs vies à la fois et je pense avoir rencontré le bug de Mr.Sautiere mais il est assez difficile à régler et vu son extrême rareté je pense pas que ce soit une priorité absolue

**Comment by Ndr6** [comment]
Tu peux expliquer le bug stp ?

**Comment by DufDuf62** [comment]
Quand la balle va vers la gauche et que son coin en haut à droite frôle le coin en bas à gauche de la brique, la briques disparaît mais la balle n'est pas dévier

**Comment by Ndr6** [comment]
Oh je vois, faudrait quand même corriger ça demain, car Mr Sautière pourrait nous tacler sur ça à l'oral ^^

**Comment by Ndr6** [comment]
Le bug survenant trop rarement, il serait trop couteux en temps de le corriger
