### ISSUE TITLE
Délai powerup qui continue pendant la pause

### ISSUE THREAD

**Issue by Ndr6** [Ndr6/Casse-Brique-ISN#30]
Après le merge #29 , ce problème apparait : 
Si on met en pause le jeu avec un powerup normalement activé, le temps restant du powerup diminue même avec la pause

**Comment by DufDuf62** [comment]
Je pense l'avoir réglé mais c'est assez dur de voir si c'est vrai

**Comment by Ndr6** [comment]
Je suis en train de regarder

**Comment by Ndr6** [comment]
Ah :/ On dirait que c'est pas bon
Maintenant, le powerup reste activé pour toujours si son moment de désactivation survient pendant la pause.
Donc il ne se désactive pas si le jeu est en pause, mais le timer doit continuer je pense

**Comment by DufDuf62** [comment]
Pour info j'ai réglé le problème mais je vais améliorer avant de commit 
PS : Merci StackOverflow

**Comment by DufDuf62** [comment]
C'est réglé
