### ISSUE TITLE
Problème d'aléatoire (powerups)

### ISSUE THREAD

**Issue by Ndr6** [Ndr6/Casse-Brique-ISN#31]
Après le merge #29 , ce problème apparait : 
La première brique cassée fait toujours apparaitre un powerup, c'est donc pas aléatoire :/

**Comment by DufDuf62** [comment]
FIN !

**Comment by Ndr6** [comment]
Peux-tu être plus précis ?

**Comment by Ndr6** [comment]
De mon côté, j'ai toujours ce bug

**Comment by DufDuf62** [comment]
Logiquement c'est réglé

**Comment by Ndr6** [comment]
Ok j'ai vu ^^
