### ISSUE TITLE
Le niveau proto ne fait pas apparaitre le type de powerup

### ISSUE THREAD

**Issue by Ndr6** [Ndr6/Casse-Brique-ISN#32]
Lié au merge #29 
Quand une brique fait apparaitre un powerup, on ne voit pas de quel powerup il s'agit.
Il faudrait utiliser les assets "capsules" de @Naijib

**Comment by DufDuf62** [comment]
Chaque powerups a son image

**Comment by Ndr6** [comment]
Je ne vois pas de changement, toujours la même capsule blanche vide
Tu as commit ?

**Comment by Ndr6** [comment]
Autant pour moi, j'avais pas vu ton commit
