### ISSUE TITLE
Changement de couleur des briques avant démarrage

### ISSUE THREAD

**Issue by Ndr6** [Ndr6/Casse-Brique-ISN#33]
En bougeant la raquette avant de lancer la balle, les briques roses deviennent vertes et redeviennent roses au lancement de la balle

**Comment by Ndr6** [comment]
Faudrait s'occuper aussi de ça en priorité, c'est assez visible et ça doit pas être compliqué à corriger, probablement une histoire de non actualisation du canvas au mouvement de la raquette

**Comment by DufDuf62** [comment]
C'est réglé en faite la fonction controls, quand elle redessiné les briques ne prenait pas en compte la vie des briques

**Comment by Ndr6** [comment]
Oh, tout s'explique
