### ISSUE TITLE
Gros ralentissement quand un powerup descend (parfois)

### ISSUE THREAD

**Issue by Ndr6** [Ndr6/Casse-Brique-ISN#46]

**Comment by DufDuf62** [comment]
Normalement c'est réglé mais il faudra vérifier Mardi sur les ordi de la salle de SI car moi j'ai jamais eu de problème sur mon ordi

**Comment by Ndr6** [comment]
Ok dac je vérifierai de mon côté :)

**Comment by Ndr6** [comment]
Je pense que le bug est réglé ici aussi

**Comment by Ndr6** [comment]
J'ai compris l'origine du bug !

**Comment by DufDuf62** [comment]
Ah d'accord et ça vient d'où ?

**Comment by Ndr6** [comment]
En gros, le navigateur ne charge pas toutes les images au chargement de la page, car il peut les charger au moment ou il en a besoin, c'est le cas avec les powerups.
Donc quand tu affiche un powerup pour la première fois, il tente apparement de télécharger l'image un grand nombre de fois car il ne l'a pas téléchargée (spam, donc ralentissement) ET quand tu changes de powerup, il n'a pas l'autre image donc il se sert de celle qu'il avait en dernier (les mauvais graphismes de PUP)

**Comment by Ndr6** [comment]
Et ça se voit que depuis le serveur en ligne et des PC avec une connexion lente (lycée) car l'image charge pas vite

**Comment by Ndr6** [comment]
![image](https://cloud.githubusercontent.com/assets/9055775/25779025/e0406c7a-330e-11e7-99e5-91808b743616.png)
![image](https://cloud.githubusercontent.com/assets/9055775/25779027/ea143ccc-330e-11e7-98d9-999b0848d56f.png)

**Comment by Ndr6** [comment]
Une solution serait de draw en dehors du canvas visible les images non utilisées pour qu'elles soient en mémoire

**Comment by DufDuf62** [comment]
D'accord j'y aurais pas pensé ! Du coup tu t'en occupe ou je le fais ?

**Comment by Ndr6** [comment]
Vas y :)

**Comment by Ndr6** [comment]
Je pense finir les effets sonores aujourd'hui et un ou 2 autres trucs

**Comment by Ndr6** [comment]
J'ai aussi changé le CDN du site en ligne, donc on a des temps de chargements moins longs pour https://isn.ender.ovh/
(Note que du coup on a le httpS et HTTP2 !)

**Comment by DufDuf62** [comment]
On peut définir 2 images  différentes e pour chaque powerups  plutôt que changer la source en plus ça pourrait régler le problème des mauvais graphismes

**Comment by Ndr6** [comment]
Aussi, mais les draw au chargement serait cool aussi

**Comment by Ndr6** [comment]
Tu avais raison, les draw n'est probablement pas nécessaire

**Comment by DufDuf62** [comment]
Logiquement c'est bon mais à revérifier mardi.
