### ISSUE TITLE
Un nom ?

### ISSUE THREAD

**Issue by Ndr6** [Ndr6/Casse-Brique-ISN#58]
Là on approche de la fin des projets, il faudrait un vrai nom au jeu.

Anthony a proposé : Ultimate Space Vikings je crois
En tout cas j'aime bien.

Proposez vos idées ici !

**Comment by Naijib** [comment]
THE WEIRDO THE GAME

**Comment by Ndr6** [comment]
Bon, à la majorité absolue de 3 voix contre une, le titre "Ultimate Space Vikings" est adopté comme nom !
Désolé Benji
