### ISSUE TITLE
Intégrer un compteur de score

### ISSUE THREAD

**Issue by Ndr6** [Ndr6/Casse-Brique-ISN#59]
Un compteur de score qui dépendrait du nombre de briques détruits (et même éventuellement d'un chain combo) serait sympa

**Comment by Apachaisan** [comment]
JAI UNE TRES BONNE IDÉE ALORS ALLEZ VOUS FAIRE METTRE

**Comment by Ndr6** [comment]
Nop, du début j'ai dit que je le ferai

**Comment by Ndr6** [comment]
Et no caps plz

Le mar. 16 mai 2017 à 12:39, Sébastien Bernard <sebas981@gmail.com> a
écrit :

**Comment by Apachaisan** [comment]
Pourquoi tu le demande ici alors ?

**Comment by Ndr6** [comment]
Pour m'en souvenir

**Comment by Ndr6** [comment]
Hors délai
