### ISSUE TITLE
Taille du canvas et nombre de briques

### ISSUE THREAD

**Issue by Ndr6** [Ndr6/Casse-Brique-ISN#60]
Il faudrait peut-être revoir à la baisse la taille du canvas, car il est trop grand pour de nombreux écrans, il faudrait peut-être enlever une colonne de briques, ça serait suffisant je pense.

Qu'est ce que vous en pensez ?

**Comment by DufDuf62** [comment]
Oui si tu veux c'est pas compliqué à changer

**Comment by Ndr6** [comment]
Ouais je me doute, c'est juste que je vois qu'on est obligés de dézoomer sur le navigateur pour jouer comfortablement

**Comment by Ndr6** [comment]
@DufDuf62 ça risque d'être compliqué avant lundi, non ?

**Comment by DufDuf62** [comment]
Il faudrait tout mettre en place avant de le faire donc si c'est près avant ce soir je peux essayer. Moi le boss est prêt il manque plus que les assets des projectiles et des briques.

**Comment by Ndr6** [comment]
ça serait trop chiant sachant que ben fait des trucs avec les combos, tu penses qu'on aura quand même le temps ?
(Au pire on dézoome pour la présentation)

**Comment by DufDuf62** [comment]
Après Lundi on va pas en sport donc c'est possible.

**Comment by Ndr6** [comment]
Ok dac

**Comment by Ndr6** [comment]
Attend, lundi on fait que des vérifs, on aura pas le temps, faut qu'on l'ait fini dimanche soir
