### ISSUE TITLE
Mauvais graphisme pour powerup

### ISSUE THREAD

**Issue by Ndr6** [Ndr6/Casse-Brique-ISN#61]
Au cours d'un playtest (de mon père, encore), j'ai remarqué que certaines capsules donnaient l'autre powerup (bleue --> Unstoppable & rouge --> Défense)

Faut voir si c'est reproductible

**Comment by DufDuf62** [comment]
C'est très bizarre

**Comment by Ndr6** [comment]
Oui, je trouve aussi, je vais tenter de reproduire ce soir

**Comment by Ndr6** [comment]
@DufDuf62 Ce bug est assez fréquent et dérangeant, tu pourrais regarder ?

**Comment by DufDuf62** [comment]
Mais je l'ai jamais eu moi !

**Comment by Ndr6** [comment]
Tente sur la version en ligne, moi ça me l'a fait juste avant manger
http://isn.ender.ovh/

**Comment by Ndr6** [comment]
Bug toujours présent :/

**Comment by Ndr6** [comment]
Lié à #46

**Comment by Ndr6** [comment]
Apparemment corrigé par @DufDuf62
