### ISSUE TITLE
Varier la trajectoire de la balle

### ISSUE THREAD

**Issue by Ndr6** [Ndr6/Casse-Brique-ISN#63]
Quand il ne reste que quelques briques, elles sont difficiles à atteindre car la trajectoire de la balle est trop "raide".

Il serait possible de : 
- Modifier l'angle légèrement et aléatoirement à chaque renvoi de la balle par la raquette
ou
- Permettre de donner un effet à la balle en la tapant avec la raquette en mouvement (selon le sens)

La deuxième option peut être plus facile à coder je pense

**Comment by DufDuf62** [comment]
Euh alors le 1er point ça doit pas poser de problème par contre le 2eme point... Le faire une fois pourquoi pas mais il faut gérer les rebond après

**Comment by Ndr6** [comment]
C'est à dire ?

**Comment by DufDuf62** [comment]
Qu'est-ce que tu appelles des effets ? Car si c'est juste changer d'angle ça va par contre si il faut faire des effets avec des trajectoires courbe c'est beaucoup plus compliqué.

**Comment by Ndr6** [comment]
Nan juste changer l'angle en fonction du sens de la balle et de la raquette

**Comment by Apachaisan** [comment]
+ faire en sorte que la balle parte vers le haut lorsqu'elle est lancée, pas vers le coté

**Comment by DufDuf62** [comment]
L'angle change maintenant
