### ISSUE TITLE
Un diapo 

### ISSUE THREAD

**Issue by Ndr6** [Ndr6/Casse-Brique-ISN#66]

**Comment by Ndr6** [comment]
Apparemment @Apachaisan est en train de commencer le diapo

**Comment by Apachaisan** [comment]
![image](https://cloud.githubusercontent.com/assets/26092948/25785294/3f711e60-337d-11e7-88f3-f9762716347e.png)
Début de diapo Prezi

**Comment by Apachaisan** [comment]
Besoin de catégories

**Comment by Ndr6** [comment]
Si j'ai bien compris, il nous faut un diapo chacun

**Comment by Ndr6** [comment]
@Apachaisan Il faut faire une présentation générale, puis parler de ce que tu as fait

**Comment by Ndr6** [comment]
J'espère que vous avez tous fini vos diapos, en tout cas bonne chance pour demain !!
