### ISSUE TITLE
Améliorer la page crédits

### ISSUE THREAD

**Issue by Ndr6** [Ndr6/Casse-Brique-ISN#84]
- Organiser les noms et les sections
- Vérifier les droits de l'image de fond
- Changer l'image de fond
- Trouver une meilleure couleur pour les noms
- Ajouter les "remerciements spéciaux"

Voilà, c'est tout je crois

**Comment by Apachaisan** [comment]
J'ai fait les meilleures couleurs

**Comment by Apachaisan** [comment]
c sur ma branche de sequoia

**Comment by Ndr6** [comment]
Fait dans la prérelease, je vais reprendre les couleurs de benji pour la master

**Comment by Apachaisan** [comment]
Je trouve que l'image de fond est très bien comme ça

**Comment by Ndr6** [comment]
Bah faut vérifier les droits, tu t'en occupes ?

**Comment by Ndr6** [comment]
Terminé
