### ISSUE TITLE
Délai Powerup Unstoppable

### ISSUE THREAD

**Issue by Ndr6** [Ndr6/Casse-Brique-ISN#85]
Il semble que parfois le Powerup Unstoppable ne dure pas réellement 5 secondes

Il faut essayer de reproduire pour voir si c'est vrai

**Comment by Apachaisan** [comment]
Aucun bug de ce genre trouvé sans utiliser de cheat (version master 09/05 8:15)

**Comment by Ndr6** [comment]
Ok dac, merci
