### ISSUE TITLE
Temps restant powerup sous forme de jauge dans le HUD

### ISSUE THREAD

**Issue by Ndr6** [Ndr6/Casse-Brique-ISN#88]
[Résultat d'un playtest]
Pour plus de lisibilité, on peut intégrer le temps restant du powerup sous forme de jauge en bas à droite du canvas

**Comment by Apachaisan** [comment]
j'ai commencé à faire un truc chelou mais voila comme je suis pas vraiment le meilleur dans le domaine je fait ce que je peut hein.
c'est sur ma branche de sequoia avec le nom assez visible.

**Comment by Ndr6** [comment]
Plus qu'a merge quasiment

**Comment by Ndr6** [comment]
Fini !
